name: jimi

on:
  push:
    branches: [ v1.4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.2]
    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir data
        cd data
        mkdir log
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/settings.json
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/sessionPub.pem
        wget https://raw.githubusercontent.com/z1pti3/jimi/v1.4/.github/workflows/sessionPriv.pem
        cd ..
        mkdir plugins
    - name: Start jimi
      run: |
        screen -dmS jimi_core python jimi_core.py  
        sleep 3s
        screen -dmS jimi_web python jimi_web.py
    - name: Tests
      run: |
        ps -aux
        curl http://127.0.0.1:5000/
        curl http://127.0.0.1:5002/
